pages:
  image: pnavaro/jupyter
  script:
    - julia --project -e `import Pkg; Pkg.instantiate()`
    - pip install nbcourse
    - nbcourse -n 1
  tags:
    - docker
    - pages
  only:
    - master
  artifacts:
    paths:
      - build
