pages:
  image: pnavaro/jupyter
  script:
    - julia --project -e 'import Pkg; Pkg.instantiate()'
    - pip install nbcourse
    - nbcourse -n 1
    - mv build public
  tags:
    - docker
    - pages
  only:
    - master
  artifacts:
    paths:
      - public
