pages:
  image: boileaum/jupyter
  script:
    - pip install nbcourse
    - nbcourse -n 5
    - mv build public
  tags:
    - docker
    - pages
  only:
    - master
  artifacts:
    paths:
      - public
